### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-fortios#15]
See details in the parent issue napalm-automation/napalm#199

**Comment by ebeahan** [comment]
Current status: 

Open PR from @ktbyers to add Python3 support into napalm-fortios:

https://github.com/napalm-automation/napalm-fortios/pull/36

Currently the napalm-fortios PR is awaiting a PR for pyfg that needs to be merged first. @dbarrosop is reaching out to the current maintainer of pyfg to try and get the PR merged.

https://github.com/spotify/pyfg/pull/13

**Comment by ebeahan** [comment]
https://github.com/napalm-automation/napalm-fortios/pull/36 was merged. 

Leaving this open as we've hit one more Python3 related issue that's currently being worked through: https://github.com/napalm-automation/napalm-fortios/issues/40

**Comment by ebeahan** [comment]
Python3 fully supported in 0.4.0 release.

**Comment by ktbyers** [comment]
Woooo hooooo :-)

**Comment by dbarrosop** [comment]
Yay! Now I will have to fix `napalm-yang` and `pyangbind` as we [I] did a step backwards there...
