### ISSUE TITLE
Error on my first merge

### ISSUE THREAD

**Issue by tedmond68** [napalm-automation/napalm-fortios#35]
Hi,
This is my first request and I'm don’t  verry comfortable with the language of shakespear, so I already apologize if I create a misunderstunding, just let me know,  I can try to correct myself.

I have in project to create a script in python for merge a modification on my router, it's a Fortinet 40C In fortiOS 5.2.9

After many days of research to understund how to use python and napalm I decided to make i try, just change the hostname on my router.

I follow the process load/replace configuration on Napalm and when I commit the config I want to merge, I have this error:

![error on merge](https://cloud.githubusercontent.com/assets/24932082/21673951/d6aec208-d32b-11e6-921d-535569ade14c.PNG)

I already correct the weak point on the preferred key exchange algorithm and I don't see an other request with this error, I'm stuck on this point.

Thanking you in advance.

**Comment by dbarrosop** [comment]
I think you might be hitting this bug:

https://github.com/paramiko/paramiko/issues/687

Details about the bug and a potential workaround is here:

https://github.com/paramiko/paramiko/issues/687#issuecomment-196577317

**Comment by mirceaulinic** [comment]
Hi @tedmond68 - after seeing this error are you able to execute any other commands?
I have never worked with fortios, probably @dbarrosop would be able to provide you more info. But looking at the error message, on the surface, I would suspect:

- either your device drops the connection (you may have a SSH timeout configured/by default)
- either the commit takes very long. Have you tried running manually the command `execute backup [...]` on the CLI?

**Comment by tedmond68** [comment]
Hi 
i try to move diffie-hellman-group1-sha1 bellow diffie-hellman-group-exchange-sha1 or just delete diffie-hellman-group1-sha1 from the tuple, and in this 2 case i have the same error...
If u have another idea let me know...

I try to find another way in netmiko waiting

**Comment by dbarrosop** [comment]
Couple of questions:
1. Are you working with a virtualenv?
2. Which file did you edit? Could you paste the whole path, please?

**Comment by tedmond68** [comment]
Hi,

Yes I work with a virtualenv.
I have edit this file: /home/tedmond/netmiko/lib/python2.7/site-packages/paramiko/transport.py

**Comment by dbarrosop** [comment]
is `/home/tedmond/netmiko` the path to your virtualenv? I have confirmation from other people the workaround works. Did you manage to get it working?

**Comment by tedmond68** [comment]
the command for activate my virtualenv  : source napalm/bin/activate,  i think i edited the wrong file no ?

**Comment by tedmond68** [comment]
ok I edited the file in /home/tedmond/napalm/local/lib/python2.7/site-packages/paramiko/trasport.py  
I moved diffie-hellman-group1-sha1 bellow diffie-hellman-group-exchange-sha1 no change and delete diffie-hellman-group1-sha1 from the tuple and still does'nt work ... :( 
Still stuck today I try again tomorrow.

**Comment by dbarrosop** [comment]
After our discusson on slack, it seems you managed to get further in the process of deploying configuration. Could you please, paste exact steps to reproduce the error you are at right now? Configuration you are using, code, traceback... It doesn't have to be exactly your code/configuration as long as it triggers your error.

**Comment by tedmond68** [comment]
Ok no worries !

My router is a FortiWiFi 40C v5.2.9,build736 (GA)
I work with python 2.7.6 on Ubuntu 14.04 in a virtulenv named napalm.
and my command step by step

>>>import napalm
>>>driver = napalm.get_network_driver('fortios')
>>>device = driver(hostname='IP', username='tedmond', password='this is not a secure password')
>>>device.open()
>>>device.load_replace_candidate(filename=config_file)

and i have this error,

![replace_candidate](https://cloud.githubusercontent.com/assets/24932082/21844103/ac9a5cc2-d7ed-11e6-827a-e029787d6fc8.PNG)

I think it's maybe because fortios doesn’t have atomic operations
for my merge i follow the same process except...

>>>device.load_merge_candidate(filename=config_file)
>>>device.commit_config()

and i have this error : 

![error on merge](https://cloud.githubusercontent.com/assets/24932082/21844340/7aab6e94-d7ee-11e6-936a-ffeac638f0be.PNG)

In my file for the merge i only have these two commands
config system global
set hostname "myhostname"

Just now i had an idea, it's maybe because my file is not on my directory napalm/ where is my virtualenv...

**Comment by dbarrosop** [comment]
I am pretty sure the problem is you are trying to change the hostname. Can you try doing something else?

**Comment by tedmond68** [comment]
Ok,

I tryed to merge what i want to merge for my project it's the firewall policy.
In my file.conf i just have my whole firewall policy and one command change,
set action accept  to deny.

This time i'm work with a FortiWiFi 30E v5.4.2,build1100 (GA)

But it wasn't impacted when i commit it, i reboot the router, i thinked maybe after a reboot i will see the change and nothing.

I'm a little confused, no error this time but  no changes....

iIf anyone has an idea, I'm will be grateful.

**Comment by dbarrosop** [comment]
I don't think either pyfg or napalm-fortios has ever been tested with FortiWifi. I don't even know which OS that device runs :P Anyway, out of curiosity, can you add `print(device.compare_config())` before the `device.commit_config()` and paste the output?

**Comment by tedmond68** [comment]
Ok 

New and last merge for this week, this time i have an error this is my traceback with a compare.config()

![last merge](https://cloud.githubusercontent.com/assets/24932082/21934671/91768ec0-d9aa-11e6-99ac-20df29beaa05.PNG)

It's sad because I'm really feeling like close to the beginning of my project... :(

Maybe next week !

Have a nice week-end !!

**Comment by tedmond68** [comment]
Just another test in my 40 C before i go

again this error... :(

![last on 40c](https://cloud.githubusercontent.com/assets/24932082/21935046/2d10b8b4-d9ac-11e6-8108-7e9d5b5876c4.PNG)

**Comment by dbarrosop** [comment]
With the same virtual environment and everything, could you try this code? (replace variables at the top of the script)

```
from pyFG.fortios import FortiOS, FortiConfig

hostname = "your_hostname_or_ip"
username = "your_user"
password = "your_passwd"
config_file = "/path/to/config"

device = FortiOS(hostname, username, password, timeout=60)
device.open()

device.candidate_config = FortiConfig('candidate')
device.running_config = FortiConfig('running')

with open(config_file) as f:
    configuration = f.read()

# Loads running config without modifying the candidate
device.load_config(empty_candidate=True)
# Loads the candidate from variable
device.load_config(in_candidate=True, config_text=configuration)

print("============== Running config:")
print(device.running_config.to_text())
print("============== Candidate config:")
print(device.candidate_config.to_text())
print("============== Diff:")
print(device.compare_config())

# Let's reload the state and print the diff
device.load_config(empty_candidate=True)
print("============== Diff:")
print(device.compare_config())

device.close()
```

That's pretty much what napalm is doing under the hoods.

**Comment by tedmond68** [comment]
I have this error 

![testdb](https://cloud.githubusercontent.com/assets/24932082/21983013/5520d27c-dbef-11e6-9ccd-7b8bb822090b.PNG)

A hint maybe ? :)

**Comment by dbarrosop** [comment]
That's the paramiko bug.

**Comment by tedmond68** [comment]
The SSH key exchange on transport. py ? :o

**Comment by dbarrosop** [comment]
It has to be. In any case, it's failing to connect.

**Comment by tedmond68** [comment]
it doesn't to be, i tryed with diffie-hellman-group1-sha1 below diffie-hellman-group-exchange-sha1 and without diffie-hellman-group1-sha1 and in this 2 case i have the same error.

**Comment by dbarrosop** [comment]
I did a small change on the script above (edited the comment). Can you try again?

**Comment by tedmond68** [comment]
Rather than writing the commands line by line I started the script.
He doesn't find pyFG.fortios
![not fund](https://cloud.githubusercontent.com/assets/24932082/21984969/e5388626-dbf8-11e6-841f-1d8c5fb22155.PNG)

**Comment by ebeahan** [comment]
I was able to replicate the `No authentication methods available` paramiko error mentioned in https://github.com/napalm-automation/napalm-fortios/issues/35#issuecomment-272849615 in my lab as well. I was able to resolve the issue by adjusting this line in the test script (note the `username=` and `password=`):

```
device = FortiOS(hostname, username=username, password=password, timeout=60)
```

We chatted back and forth a bit on Slack about the most recent `ImportError`. Worst case I would just create a new virtualenv, re-install `napalm` in the new virtualenv, and then attempt to run the test script from the new virtualenv if you continue to encounter the `ImportError` issues.

**Comment by tedmond68** [comment]
Ok thanks @ebeahan, something wrong with line 18: 

![line 18](https://cloud.githubusercontent.com/assets/24932082/22018015/066913f6-dcad-11e6-9add-13c97f5f4fbb.PNG)

**Comment by dbarrosop** [comment]
You are back at square 1, please, review the thread as that's an error we have already discussed.

In any case, this is an error completely unrelated to napalm.

**Comment by ebeahan** [comment]
@tedmond68 Any luck working through the SSH timeouts? As @dbarrosop mentioned it doesn't look like a napalm-specific issue, but appears that the underlying SSH session is timing out to the Fortinet device.

**Comment by tedmond68** [comment]
No progress on that, i tried with netmiko and it works, it's just less easier for me. :p 
To bad i work with fortinet, i hate those equipements. :p 
I don't understand why my boss chosen Fortinet...
Thanks for asked me and to tried to help me both of you.

**Comment by ebeahan** [comment]
Ok will go ahead and close out the issue.
