### ISSUE TITLE
FortiOS 5.4 no SSH connection

### ISSUE THREAD

**Issue by awlx** [napalm-automation/napalm-fortios#48]
###Description of Issue/Question
I cannot connect to FortiOS 5.4 with napalm. FortiOS 5.2 works without a problem. 

### Setup
```
Python 2.7.13
```
### napalm-fortios version
```
pip2 freeze | grep napalm
napalm==1.2.0
napalm-base==0.24.3
napalm-eos==0.6.0
napalm-fortios==0.4.0
napalm-ios==0.7.0
napalm-iosxr==0.5.4
napalm-junos==0.12.0
napalm-nxos==0.6.0
napalm-panos==0.4.0
napalm-pluribus==0.5.1
napalm-ros==0.2.2
napalm-vyos==0.1.3
```

### Steps to Reproduce the Issue
device.open()

### Error Traceback
>>> device.open()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/napalm_fortios/fortios.py", line 42, in open
    self.device.open()
  File "/usr/local/lib/python2.7/site-packages/pyFG/fortios.py", line 103, in open
    self.ssh.connect(**cfg)
  File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 394, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 649, in _auth
    raise saved_exception
paramiko.ssh_exception.AuthenticationException: Authentication failed.

Any idea? I checked the password 20 times, and it works when I manually SSH to it. It also works without problems with FortiOS 5.2 machines.

**Comment by dbarrosop** [comment]
Looks like this: spotify/pyfg/pull/17

Make sure you are running latests versions of all the libraries and let us know if that fixed the problem.

**Comment by awlx** [comment]
Setting dh-param to 1024 helped. Thanks :).

**Comment by dbarrosop** [comment]
Glad to hear :D
