### ISSUE TITLE
ownership for the fortios driver

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-fortios#50]
Hello,
community drivers are going to be maintained by the community or considered deprecated and unmaintained. For that reason we are looking for people willing to maintain this repo. Owners will have full admin rights on this repo and on its pypy package.

Pinging top contributors to see if they are interested: @ebeahan @awlx @lokespotify  

If you have questions/comments let me know.

Regards

**Comment by dbarrosop** [comment]
Adding @StefanLindblom as he is maintaining `pyfg` (I think) so he might be interested in this.

**Comment by awlx** [comment]
Hello,

I would be interested as I am going to add some more support for FortiOS anyway.

I just don't know the timeline yet. But I hope to find some time around Christmas.

**Comment by dbarrosop** [comment]
Ok, let me know then if you want to be the maintainer and I will give you access to both this repo and pypi, I will need your pypi username :)

**Comment by awlx** [comment]
My pypi username is awlnx. :)

Thank you :)

**Comment by dbarrosop** [comment]
Done! It's all yours, please, verify and feel free to reopen if there is any issue.
