### ISSUE TITLE
No class inheriting "napalm.base.base.NetworkDriver"

### ISSUE THREAD

**Issue by cofonseca** [napalm-automation/napalm-fortios#52]
### Description of Issue/Question
I'm trying to use Napalm to connect to a Fortigate firewall. I'm at the very first step of attempting to import the driver using napalm, and receive an error. I've tried this on three different computers, all running the latest version of Python3. I installed both Napalm and Napalm-Fortios using pip.

When I run napalm.get_network_driver('fortios'), I receive an error that says:
napalm.base.exceptions.ModuleImportError: No class inheriting "napalm.base.base.NetworkDriver" found in "napalm.fortios"

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
- [X] Yes
- [ ] No

### napalm-fortios version
(Paste verbatim output from `pip freeze | grep napalm-fortios` between quotes below)

```
napalm-fortios==0.4.0
```

### Steps to Reproduce the Issue

import napalm
napalm.get_network_driver('fortios')

Screenshot: http://prntscr.com/if3yct

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\napalm\base\__init__.py", line 106, in get_network_driver
    .format(install_name=module_install_name))
napalm.base.exceptions.ModuleImportError: No class inheriting "napalm.base.base.NetworkDriver" found in "napalm.fortios".
```
Screenshot: http://prntscr.com/if3yct

**Comment by billyblue52** [comment]
Same issue for me, any update?

**Comment by dbarrosop** [comment]
Can you try installing the develop branch? I think the fix is there.

@awlx could you release a new version with #51

**Comment by billyblue52** [comment]
I will try that, Thank you.

Sorry I git cloned the dev repo although I am unsure how to install.

Many Thanks
________________________________

**Comment by billyblue52** [comment]
Thanks all working now
________________________________

**Comment by awlx** [comment]
Released a new version which should fix the problem.

**Comment by cofonseca** [comment]
The new version worked perfectly. Thank you!
